name: Lint & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run `astro check`
        run: pnpm check
        continue-on-error: true

      # - name: Run tests
      #   run: pnpm run test
